### ISSUE TITLE
TGM v0.1.0  Roadmap

### ISSUE THREAD

**Issue by edgarriba** [arraiy/torchgeometry#1]
This is the roadmap for torchgeometry v0.1.0 focuses on multi-view reprojection primitives that work on images and feature maps.

- Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list).

**Features**
- API
    - Pinhole
        - [x] inverse_pose 001097c3af11a44f18bb8e66e32bf73362d12046
        - [x] pinhole_matrix 063b0c611217c6fcdf1f43a98f4934220d2f54df
        - [x] inverse_pinhole_matrix 063b0c611217c6fcdf1f43a98f4934220d2f54df
        - [x] scale_pinhole 063b0c611217c6fcdf1f43a98f4934220d2f54df
        - [x] homography_i_H_ref 063b0c611217c6fcdf1f43a98f4934220d2f54df
    - Conversions
        - [x] pi fb56c9c800b347392737d2342e8938ef88cd25e1
        - [x] rad2deg fb56c9c800b347392737d2342e8938ef88cd25e1
        - [x] deg2rad fb56c9c800b347392737d2342e8938ef88cd25e1
        - [x] convert_points_from_homogeneous f13c462326cb6f0c558b91f1a25a457a6bc107b6
        - [x] convert_points_to_homogeneous f13c462326cb6f0c558b91f1a25a457a6bc107b6
        - [x] transform_points 1a1511c906e547eedc63f0c363d3aa9a9155b471
        - [x] angle_axis_to_rotation_matrix 4c929d528ac65dbab04a7388549ee903013b8e1f
        - [x] rtvec_to_pose 4c929d528ac65dbab04a7388549ee903013b8e1f
        - [x] rotation_matrix_to_angle_axis f999165bf3b850ea35d3758196b90b75631f85fb
        - [x] rotation_matrix_to_quaternion f999165bf3b850ea35d3758196b90b75631f85fb
        - [x] quaternion_to_angle_axis f999165bf3b850ea35d3758196b90b75631f85fb
    - Warping
        - [x] HomographyWarper 2e54229fbb7b14a071d3dd2ad93103c68791f57a
        - [x] DepthWarper cd0356977a0fb573e78f0ba59cf490671eb56a24
    - Utilities
        - [x] tensor_to_image 3ad7d0518365a0f7f12c3e6f5d29e3b2605974c2
        - [x] image_to_tensor 3ad7d0518365a0f7f12c3e6f5d29e3b2605974c2
        - [x] inverse 1a1511c906e547eedc63f0c363d3aa9a9155b471
- Testing
    - [x] docker kit ae8d9e1adb68cb282ce4165132ab701e96a33497
    - [x] automated test with TravisCI c213e3e348a6ba553fa2323e4e897659d0250f60
    - [x] lint tests c213e3e348a6ba553fa2323e4e897659d0250f60
    - [ ] cuda tests (v0.1.1)
- Documentation
    - [x] sphinx documentation b9251ab28b33023dbab862d210aea20a96545b0d
    - [x] development e800c3609e64b4297c9713d209d1527c7841f627
- Examples:
    - [x] homography regression ce1524df7aedb4c7abff8f5b0bd9ff6a89f35422
    - [x] image warped by depth f999165bf3b850ea35d3758196b90b75631f85fb
    - [x] jupiter notebooks 3c96835b02bb4dfd30eec3f33c996373aa6584ca

**Comment by ankurhanda** [comment]
I will be more than happy to add new functionality to it --- robot kinematics and other stuff that I have already implemented but in tensorflow :) so we could import both gvnn and that as well.
