### ISSUE TITLE
TGM v0.1.1 Roadmap (short-term)

### ISSUE THREAD

**Issue by edgarriba** [arraiy/torchgeometry#15]
This is the roadmap for short-term torchgeometry v0.1.1 focuses PyTorch 1.0.0 support, bug fixes and code clean up. 

Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list).

## Features

- **Support PyTorch 1.0.0**  3ee14c83285f05ce8d29725a0489d0c9f8b058ed

- **Bug fixes**
  - [x] test_homography_i_H_ref crashes 0aba15d0b3ea79cfc3ed6a31ba088f86db643658

- **Test**
  - [ ] **Support Codecov**
  - [x] Add type checking to functions
  - [x] Enable batched version to functions

- **Installation**
  - [x] pip packages
